     This is an automated email.  Do not reply.

     A possible pre-eruption uplift signal has been detected by
     an OOI/RSN/BOTPT instrument at Axial Seamount (a rate of
     pressure-depth change greater than +10 cm/hr in the last
     10-20 minutes).  Based on past experience, this may indicate
     that magma is intruding to the surface and an eruption may
     begin within the next hour.  Check the data to confirm at
     https://www.pmel.noaa.gov/eoi/rsn/index.html
